[package]
authors = ["Todd Nguyen"]
edition = "2018"
name = "sorting_algos"
version = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
pretty_assertions = "0.7"
