name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust/dependency-inversion/sorting-algos
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
      run:
        working-directory: rust/dependency-inversion/sorting-algos
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
