name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust/dependency-inversion/sorting-algos
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust/dependency-inversion/sorting-algos
    steps:
    - name: Run tests
      run: cargo test --verbose
